# Generated by Django 4.2.17 on 2025-01-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_userprofile_full_name_alter_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(default="Anonymous", max_length=100),
        ),
    ]
